### ISSUE TITLE
User Story 1 - List of Activities

### ISSUE THREAD

**Issue by Volkerboehm1971** [Volkerboehm1971/activities-app#2]
## Value proposition
**As a** user,
**I want to** see a list of all activities,
**so that** I find inspiration for my next activities.

## Description
![Image](https://github.com/Volkerboehm1971/activities-app/assets/160751770/0beb5127-dadc-4c70-bcdc-b22e6d4c27e2)

## Acceptance criteria
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?

## Tasks
- [ ] Create feature branch `feature/list-overview`
- [ ] Create ActivityCard-component with props 'key value: id', 'image', 'title', 'area'
- [ ] Import `dummydata.json`
- [ ] Create a an unordered list and map over dummy data
- [ ] Display each activity in a ActivityCard in a list at the HomePage
- [ ] Create `<h1>` headline with text `List of activities`
