### ISSUE TITLE
User Story 3 - Create new Activity

### ISSUE THREAD

**Issue by Jessica-Windoffer** [Volkerboehm1971/activities-app#5]
# Create Activity

## Value Proposition

**As a** user,
**I want to** create my own personal activities,
**so that** I have quick access to them every time in the future.

## Description

![Image](https://github.com/Volkerboehm1971/activities-app/assets/160733504/990179f4-b49a-418f-a57e-e403da31dd75)

## Acceptance Criteria

- The form is headlined "Create a new activity" highlighting its purpose.
- The form must include labeled fields for activity
  - `title`
  - `category` (e.g. "Outdoor")
  - ... (corresponding to your data model)
- The activity `title` is mandatory, with a character limit between 1 and 150.
- The `category` field must have a default option, "Please select a category" and require a selection.
- Upon form submission, the new activity is added to the top of the activities list.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.

### Tasks

- [x] Create feature branch `feature/create-activity`
- [x] Create `<h1>` headline with text `List of activities`
- [x] Create `text`-`input-field` and `label` for `title`-field
- [x] Create `select`-`element` and `label` for `category`-selection
- [x] Create `text`-`input-field` and `label` for `area`-field
- [x] Create `text`-`input-field` and `label` for `country`-field
- [x] Create `text`-`input-field` and `label` for `description`-field
- [x] Create `image`-`upload-field` and `label` for `image`-upload
- [x] Set requirements for each field to `required`
- [x] Additional requirements for `title`-field: `min=1`, `max=150`
- [x] Additional requirements for `category`-selection: defaultValue="Please select a category"
- [ ] Create error message if any fields are empty at form submission
- [x] Create a button to the bottom of the page with `Add Activity` as text
- [ ] Write a function that re-renders the new state after clicking the `Add Activity`-`button`
- [ ] Show the updated list after button `Add Activity` is clicked
