### ISSUE TITLE
Visual adaption of forms „Create“ and “Edit“

### ISSUE THREAD

**Issue by Volkerboehm1971** [Volkerboehm1971/activities-app#68]
## Value Proposition
**As a** User,
**I want to** see the see the forms a bit more narrow,
**so that I** have more air and it looks prettier.

## Description

![Image](https://github.com/Volkerboehm1971/activities-app/assets/160751770/02a3136d-5fe2-4146-be3a-e6a0ee540edc)

## Acceptence Criteria
- By shortening the forms the page gets a lot more lighter and prettier
- There is no need to write long text in the input fields

## Tasks
- [ ] Create feature branch “Visual adaption of forms“
- [ ] In mobile view the forms need a margin like the cards in “List of activities“ have
- [ ] Try to make it a bit more “responsive“ by using max-width: 400px in style.js
- [ ] Use gap
