### ISSUE TITLE
US - Responsive Design for Tablet

### ISSUE THREAD

**Issue by Volkerboehm1971** [Volkerboehm1971/activities-app#72]
## Value Proposition
**As a** User,
**I want to** use the app on a Tablet
**so that I** am not tied to a Smartphone and I am more flexible in the Usage.

## Description
_As this User Story is mainly based on "Try and Error" and adjusting/arranging content in the progress itself so it is visually appealing, no satisfactory pictorial description can be given at this point._

## Acceptance Criteria
- The Design - initially designed for _Mobile First_ - is adapted for **common Tablet screen sizes** responsively as well as optimized for the larger screen
- Design in this case means: Arrangement of content is adjusted to the screen size
   _-> E.g. List of Activities is no longer a One-Column arrangement but rather a Two- or Three-Column arrangement
   -> E.g. the forms of "create" and "edit" might be re-arranged as well_
- The Navigation Bar as well as the Buttons are adapted so they are large enough for the changed touch interaction

## Tasks
- [ ] Create feature branch `feature/responsive-tablet`
- [ ] Define Breakpoints / Media queries → Decision after Research: _Tablet Breakpoint: from 768px to 1024px_; _Design visually adapted on iPad Pro_
- [ ] Re-arrange the components of each Page in order to create an adapted and more appealing Design on Tablet Screen
- [ ] Testing (e.g using DevTools or available Tablet) to guarantee proper adjustments
