### ISSUE TITLE
US - Responsive Design for Desktop

### ISSUE THREAD

**Issue by Volkerboehm1971** [Volkerboehm1971/activities-app#73]
## Value Proposition
**As a** User,
**I want to** use the app not only on a Tablet or Smartphone but on a Desktop as well
**so that I** am not tied to a small Display and I am even more flexible in the Usage.

## Description
_As this User Story is mainly based on "Try and Error" and adjusting/arranging content in the progress itself so it is visually appealing, no satisfactory pictorial description can be given at this point as well as on the User Story for the Responsive Design for Tablets._

## Acceptance Criteria
- The Design - initially designed for _Mobile First_ and previously adapted to a Tablet Screen - is now adapted for **common Browser / Laptop/ External Desktop sizes** responsively
- Design in this case also means: Arrangement of content is adjusted to the screen size
   _-> E.g. List of Activities is no longer a Two- or Three-Column arrangement but rather a Three- or Four-Column arrangement
   -> E.g. the forms of "create" and "edit" might be re-arranged again
   -> The Navigation Bar might be visually/located/re-arranged to a different appearance_
- Using the App on the Desktop enables hover and cursor effects for Buttons and Links

## Tasks
- [ ] Create feature branch `feature/responsive-desktop`
- [ ] Define Breakpoints / Media queries → Decision after Research: _Desktop Breakpoint: from 1025px to open end_; _Design visually adapted on MacBook Pro 16" Full Screen Browser Window_
- [ ] Re-arrange the components of each Page in order to create an adapted and more appealing Design on a Desktop Screen
       _-> E. g.: For the Navigation Bar a Burger Menu might be an appropriate solution to think about?_
- [ ] Implement hover and cursor effects for Buttons and Links
- [ ] Testing (e.g using the Browser on the Laptop/ External Desktop) to guarantee proper adjustments
